### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by FCO** [FCO/Red#151]
```
<Altai-man_> sorry for the delay... actually, I am observing a memory leak, and a totally insane one, in a couple of seconds my 16 gb of RAM are full and the box is completely unuseable
22:11 so I am enabling an oom killer right now
22:13 ⇐ sena_kun quit  •  Altai-man_ → sena_kun  
22:45 S<sena_kun> so if I add `Model.first(*.sessionid eq $session-id)` it starts to leak and is killed after a second
22:46 MoarVM panic: Memory allocation failed; could not allocate 366544 bytes
Monday, April 22nd, 2019
00:17 S<sena_kun> I am getting `No data to be updated on object of type 'UserSession'.`
00:18 I wonder if it should throw at all.
```

**Comment by jonathanstowe** [comment]
Is this the problem with not using  ```Red::Operators``` as per #100 ?

**Comment by FCO** [comment]
I don't know... I haven't tested that yet...

**Comment by jonathanstowe** [comment]
This may have gone away with the "being more frugal with stringification" thing that was fixed a while back.

**Comment by FCO** [comment]
Thanks!

**Comment by jonathanstowe** [comment]
The oroblem with not loading Red::Operators and the stringifaction were related in asmuch as if you ended up with e.g. the plain `eq` that doesn't know about the `Red::AST` versions it would end up stringifying the whole `ResultSeq` and because that stringified the relations to any depth this would blow up quickly.
