### ISSUE TITLE
Pg driver doesn't refresh relations upon .^create

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#168]
Let's get straight to the code:

```
model Test {
    has UInt $.id is serial;
    has Str $.name is column;
    has UInt $.parent-id is referencing{ Test.id };

    has Test $.parent is relationship{ .parent-id };
}

Test.^create-table: :if-not-exists;

my $parent = Test.^create: :name("parent");
my $child = Test.^create: :name("child"), :parent-id($parent.id);

note "child has parent: ", $child.parent.defined;

$child = Test.^find: name => 'child';

note "reloaded child has parent: ", $child.parent.defined;
```

When used with SQLite I get:

>```
>child has parent: True
>reloaded child has parent: True
>```

When used with `Pg`:

>```
>child has parent: False
>reloaded child has parent: True
>```

Clearly, `$.parent` is not updated.

**Comment by FCO** [comment]
This occurs because we try to avoid running a new query after creating a new row on SQLite returning a Proxy (on SQLite there is no `RETURNING *` on insert, so we need to run a new query to get the created row). The FETCH on that Proxy run the query, that's why it get the new data. On Postgres, we just use a `RETURNING *` on the insert, so we don't need to run another query, so we do not return a Proxy...
@vrurg How do you think we should fix it?
And thank you for your issue! :)

**Comment by vrurg** [comment]
I was writing this on IRC and can't come up with any better idea. A `relationship` attribute must be lazy (via `Proxy`). This way it would be initialized when referenced. And basically that's the only valid way. Imagine a situation when records in a database form a chain. I one needs to walk down the chain it doesn't mean all records are to be fetched at once, right? 

There is a performance penalty of using `Proxy`. In `AttrX::Mooish` I worked around it by replacing an attribute container with actual content (containerized, of course :) ) when initialized and restoring it back into `Proxy` state when cleaned up. You may consider doing it similar way.

**Comment by FCO** [comment]
The relationship is a Proxy... but the “parent obj” isn’t, so the foreign key is the one it was gotten on the first time (on Pg, on SQLite the “parent obj” IS a proxy, so it selects all the data (including the foreign key) every time)

I’ve read AttrX::Mooish while I was writing this part... I’m pretty sure I’ve stolen that from you...

But what I mean is: the problem here isn’t the relationship, but the foreign key that (if we do not return a Proxy on .^create) will always be the same...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment]
I think I got everything wrong... I'll take another look and I'll answer again...

**Comment by vrurg** [comment]
My point is that any `relationship` kind of attribute must be lazy. So this way we run a select query only when needed. Hope I managed to explain it right.

**Comment by FCO** [comment]
could you test it now, please?

**Comment by vrurg** [comment]
Next week, hopefully. Too busy these days.

**Comment by vrurg** [comment]
I have finally managed to run the code. It was failing due to problems with re-exporting symbols via `EXPORT` sub. If perl6/problem-solving#74 will be accepted and rakudo/rakudo#3076 is merged I would submit another PR for you where instead of `%()` in `EXPORT` it will use `()::`.

Anyway, as my code is now running, I can confirm that the problem of this ticket is most likely solved. I now see all DB records accompanied with data from their parents where previously some were reported as incomplete. No deeper investigation though because I'm still on tight schedule. ;)

Thank you!

**Comment by FCO** [comment]
Thank you very much!
