### ISSUE TITLE
trait_mod:<is>(Mu $model, Mu:U :populated-by($role))

### ISSUE THREAD

**Issue by FCO** [FCO/Red#434]
Maybe also:

```raku
trait_mod:<is>(Mu $model, :&populated-by)
```

**Comment by jonathanstowe** [comment]
I'm not quite sure what this one is addressing, if its intent is to populate a bunch of default value (possibly dynamically,) then it probably wants to be called `defaulted-by` and take a Routine that takes the supplied arguments to `^create` and returns a hash of the actually arguments that will be used.

On the other if the intent is to create a bunch of new rows then it's probably a `^populate` rather than a trait which takes a list of hash and generates a `INSERT INTO Foo ( .... ) VALUES (....), (....)`

**Comment by FCO** [comment]
The intent were to add another option to ^populate (https://github.com/FCO/Red/blob/master/lib/Red/Cli.pm6#L145), but now I’m rethinking it… I don’t think that’s needed… I’ll close this issue, thanks! (Unless you disagree)

**Comment by jonathanstowe** [comment]
Got ya!
