### ISSUE TITLE
Should a ^create-table create all related tables too?

### ISSUE THREAD

**Issue by FCO** [FCO/Red#83]

**Comment by jonathanstowe** [comment]
There's a small catch with that (and actually with creating mutually dependent tables,) if you have something like:

```perl6
use Red;

model State { ... }
model Workflow {
    has Int     $.id                is serial;
    has Str     $.name              is column(:unique);
    has Int     $.initial-state-id  is referencing({ State.id });
    has State   $.initial-state     is relationship({ .initial-state-id });
    has State   @.states            is relationship({ .workflow-id });
}

model State is table('whatever')  {
    has Int         $.id            is serial;
    has Str         $.name          is column;
    has Int         $.workflow-id   is referencing({ Workflow.id });
    has Workflow    $.workflow      is relationship({ .workflow-id });
}

my $*RED-DEBUG          = $_ with %*ENV<RED_DEBUG>;
my $*RED-DB             = database "SQLite", |(:database($_) with %*ENV<RED_DATABASE>);

Workflow.^create-table;
State.^create-table;
```

You get SQL like:

```
SQL : CREATE TABLE workflow(
   initial_state_id integer NULL references whatever(id),
   name varchar(255) NOT NULL,
   id integer NOT NULL primary key AUTOINCREMENT,
   UNIQUE (name)
)
SQL : CREATE TABLE whatever(
   workflow_id integer NULL references workflow(id),
   id integer NOT NULL primary key AUTOINCREMENT,
   name varchar(255) NOT NULL
)
```

Which works fine for SQLite as it doesn't really worry too much about the references, but with, say, Pg that SQL would blow up because the ```whatever```  that is referenced by the ```initial-state-id``` doesn't exist at that point.

If one was doing that by hand one would omit the forward reference when creating the ```workflow``` table and then alter the table to create the reference after the ```whatever``` table had been created.

The easiest way to handle that would be to omit adding the foreign key constraints from all the table creations and have them made in a separate statement, then it would be easier to order the statements by dependencies.

BTW SQLite, Pg and Oracle don't worry about creating a table called ```state``` but  Red doesn't like it.

**Comment by FCO** [comment]
Yes, that is something I think make ^create-table create all related tables would help...

About the state, I bot a list of all "forbidden" words on sql... I think that's the case of removing state from it and add it only on the driver where its not accepted.

**Comment by FCO** [comment]
I mean: ^create-table (or any other name) would create every table without the fk columns, and after that alter each table to add the fk columns

**Comment by FCO** [comment]
Sone by `schema(...).create`
