### ISSUE TITLE
Pandas

### ISSUE THREAD

**Issue by FCO** [FCO/Red#93]
I was reading about pandas (the python lib) and it looks a lot the Red, but with out a database... would it be interesting to create a driver that do not use any database and do everything on memory?

**Comment by MattOates** [comment]
Thats not what or why people use Pandas so much I dont think. In memory is almost a limitation rather than necessarily a desired trait. Its more all of the added value with plotting and integration with analytics libraries. A cheap way to go in memory is just use SQLite in memory. If Pandas is your inspiration Id look to the future of that project Apache Arrow and to a lesser extent Feather. Creating an Arrow driver for Red would add ecosystem compatibility for data scientists.

**Comment by FCO** [comment]
I think you are right! and we already use SQLite for that intent today.
Thanks for helping and for telling about the Arrow.

Thanks!
